const PDFDocument = require('pdfkit');

/**
 * Generate a branded Project Charter PDF
 *
 * @param {Object} charter - ProjectCharter document (populated)
 * @param {Object} project - Project document (populated)
 * @returns {Buffer} PDF buffer
 */
const generateCharterPDF = async (charter, project) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];

    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Brand Header ──
    doc.rect(0, 0, doc.page.width, 80).fill('#2D55FF');
    doc.fontSize(24).fillColor('#FFFFFF').text('D360', 50, 25, { continued: true });
    doc.fontSize(10).text('  by Dawat IT & Consultancy', { baseline: 'bottom' });
    doc.fontSize(16).fillColor('#FFFFFF').text('PROJECT CHARTER', 50, 50);

    doc.moveDown(3);
    doc.fillColor('#1A1A2E');

    // ── Project Info ──
    doc.fontSize(12).font('Helvetica-Bold').text('Project Information');
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
    doc.moveDown(0.5);

    const info = [
      ['Project Code', project.projectCode || 'N/A'],
      ['Project Name', project.name],
      ['Client', project.client?.name || 'N/A'],
      ['Project Type', project.projectType || 'N/A'],
      ['Priority', project.priority || 'N/A'],
      ['Start Date', project.startDate ? new Date(project.startDate).toLocaleDateString() : 'TBD'],
      ['Target End Date', project.targetEndDate ? new Date(project.targetEndDate).toLocaleDateString() : 'TBD'],
      ['Estimated Budget', `${project.currency || 'BDT'} ${(project.estimatedBudget || 0).toLocaleString()}`],
    ];

    doc.font('Helvetica').fontSize(10);
    info.forEach(([label, value]) => {
      doc.font('Helvetica-Bold').text(`${label}: `, { continued: true });
      doc.font('Helvetica').text(value);
    });

    // ── Business Case ──
    if (charter.businessCase?.problem) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('Business Case');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
      doc.moveDown(0.5).fontSize(10).font('Helvetica');

      if (charter.businessCase.problem) {
        doc.font('Helvetica-Bold').text('Problem: ', { continued: true });
        doc.font('Helvetica').text(charter.businessCase.problem);
      }
      if (charter.businessCase.proposedSolution) {
        doc.font('Helvetica-Bold').text('Proposed Solution: ', { continued: true });
        doc.font('Helvetica').text(charter.businessCase.proposedSolution);
      }
      if (charter.businessCase.expectedBenefits) {
        doc.font('Helvetica-Bold').text('Expected Benefits: ', { continued: true });
        doc.font('Helvetica').text(charter.businessCase.expectedBenefits);
      }
    }

    // ── Objectives ──
    if (charter.objectives?.length > 0) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('Project Objectives');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
      doc.moveDown(0.5).fontSize(10).font('Helvetica');
      charter.objectives.forEach((obj, i) => {
        doc.text(`${i + 1}. ${obj.description}`);
      });
    }

    // ── Scope ──
    doc.moveDown(1);
    doc.fontSize(12).font('Helvetica-Bold').text('Scope Definition');
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
    doc.moveDown(0.5).fontSize(10);

    if (charter.inScope?.length > 0) {
      doc.font('Helvetica-Bold').text('In Scope:');
      doc.font('Helvetica');
      charter.inScope.forEach(s => doc.text(`  • ${s}`));
    }
    if (charter.outOfScope?.length > 0) {
      doc.moveDown(0.3).font('Helvetica-Bold').text('Out of Scope:');
      doc.font('Helvetica');
      charter.outOfScope.forEach(s => doc.text(`  • ${s}`));
    }

    // ── Approval ──
    doc.moveDown(2);
    doc.fontSize(12).font('Helvetica-Bold').text('Approval');
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
    doc.moveDown(0.5).fontSize(10).font('Helvetica');
    doc.text(`Status: ${charter.charterStatus?.toUpperCase() || 'DRAFT'}`);
    if (charter.approvedBy?.name) {
      doc.text(`Approved By: ${charter.approvedBy.name}`);
    }
    if (charter.approvedDate) {
      doc.text(`Approved Date: ${new Date(charter.approvedDate).toLocaleDateString()}`);
    }

    // ── Footer ──
    doc.moveDown(2);
    doc.fontSize(8).fillColor('#999999')
      .text(`Generated by D360 — Dawat IT & Consultancy | ${new Date().toLocaleString('en-BD', { timeZone: 'Asia/Dhaka' })}`, 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  });
};

module.exports = { generateCharterPDF };
