const PDFDocument = require('pdfkit');

const RAG_COLORS = { green: '#10B981', amber: '#F59E0B', red: '#EF4444' };

const generateStatusReportPDF = async (report, project) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill('#2D55FF');
    doc.fontSize(20).fillColor('#FFFFFF').text('PROJECT STATUS REPORT', 50, 20);
    doc.fontSize(10).text(`Report #${report.reportNumber} | ${new Date(report.reportDate).toLocaleDateString()}`, 50, 48);
    doc.fontSize(10).text(`${project.name} (${project.projectCode})`, 50, 62);

    doc.moveDown(4).fillColor('#1A1A2E');

    // RAG Summary
    doc.fontSize(12).font('Helvetica-Bold').text('RAG Status Summary');
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
    doc.moveDown(0.5).fontSize(10).font('Helvetica');

    const rags = [
      ['Overall', report.overallRag],
      ['Schedule', report.scheduleRag],
      ['Budget', report.budgetRag],
      ['Scope', report.scopeRag],
      ['Quality', report.qualityRag],
      ['Risk', report.riskRag],
    ];
    rags.forEach(([label, rag]) => {
      const color = RAG_COLORS[rag?.status] || '#999';
      doc.circle(doc.x + 5, doc.y + 5, 4).fill(color);
      doc.fillColor('#1A1A2E').text(`  ${label}: ${(rag?.status || 'N/A').toUpperCase()} — ${rag?.reason || ''}`, doc.x + 15);
    });

    // Executive Summary
    if (report.executiveSummary) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('Executive Summary');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
      doc.moveDown(0.5).fontSize(10).font('Helvetica').text(report.executiveSummary);
    }

    // Progress
    if (report.progressThisPeriod?.length > 0) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('Progress This Period');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
      doc.moveDown(0.5).fontSize(10).font('Helvetica');
      report.progressThisPeriod.forEach(p => doc.text(`• ${p}`));
    }

    if (report.planNextPeriod?.length > 0) {
      doc.moveDown(0.5);
      doc.fontSize(12).font('Helvetica-Bold').text('Plan for Next Period');
      doc.moveDown(0.3).fontSize(10).font('Helvetica');
      report.planNextPeriod.forEach(p => doc.text(`• ${p}`));
    }

    // Budget Snapshot
    if (report.budgetSnapshot) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('Budget Snapshot');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
      doc.moveDown(0.5).fontSize(10).font('Helvetica');
      doc.text(`Planned: ৳${(report.budgetSnapshot.plannedToDate || 0).toLocaleString()}`);
      doc.text(`Actual: ৳${(report.budgetSnapshot.actualToDate || 0).toLocaleString()}`);
      doc.text(`Variance: ৳${(report.budgetSnapshot.variance || 0).toLocaleString()}`);
    }

    // Footer
    doc.fontSize(8).fillColor('#999999')
      .text(`Generated by D360 — Dawat IT & Consultancy | ${new Date().toLocaleString('en-BD', { timeZone: 'Asia/Dhaka' })}`, 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  });
};

module.exports = { generateStatusReportPDF };
