const PDFDocument = require('pdfkit');

const generateClosureReportPDF = async (closure, project, lessonsLearned) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', chunk => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.rect(0, 0, doc.page.width, 80).fill('#1A1A2E');
    doc.fontSize(20).fillColor('#FFFFFF').text('PROJECT CLOSURE REPORT', 50, 20);
    doc.fontSize(10).text(`${project.name} (${project.projectCode})`, 50, 48);
    doc.fontSize(10).text(`Closure Type: ${(closure.closureType || 'successful').toUpperCase()}`, 50, 62);

    doc.moveDown(4).fillColor('#1A1A2E');

    // Project Summary
    doc.fontSize(12).font('Helvetica-Bold').text('Project Summary');
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
    doc.moveDown(0.5).fontSize(10).font('Helvetica');
    doc.text(`Client: ${project.client?.name || 'N/A'}`);
    doc.text(`Duration: ${project.actualDurationDays || project.estimatedDurationDays || 'N/A'} days`);
    doc.text(`Final Status: ${project.overallStatus}`);

    // Financial Summary
    if (closure.financialClosure) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('Financial Closure');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
      doc.moveDown(0.5).fontSize(10).font('Helvetica');
      doc.text(`Budget: ৳${(closure.financialClosure.finalBudget || 0).toLocaleString()}`);
      doc.text(`Actual Spent: ৳${(closure.financialClosure.finalSpent || 0).toLocaleString()}`);
      doc.text(`Variance: ৳${(closure.financialClosure.variance || 0).toLocaleString()}`);
    }

    // Sign-off
    doc.moveDown(1);
    doc.fontSize(12).font('Helvetica-Bold').text('Sign-Off');
    doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
    doc.moveDown(0.5).fontSize(10).font('Helvetica');
    doc.text(`Sponsor Signed: ${closure.signOff?.sponsorSigned ? 'YES' : 'NO'}`);
    doc.text(`Client Signed: ${closure.signOff?.clientSigned ? 'YES' : 'NO'}`);

    // Lessons Learned Summary
    if (lessonsLearned) {
      doc.moveDown(1);
      doc.fontSize(12).font('Helvetica-Bold').text('Key Lessons Learned');
      doc.moveTo(50, doc.y).lineTo(545, doc.y).stroke('#2D55FF');
      doc.moveDown(0.5).fontSize(10).font('Helvetica');

      if (lessonsLearned.whatWentWell?.length > 0) {
        doc.font('Helvetica-Bold').text('What Went Well:').font('Helvetica');
        lessonsLearned.whatWentWell.slice(0, 5).forEach(w => doc.text(`  ✓ ${w}`));
      }
      if (lessonsLearned.whatDidntGoWell?.length > 0) {
        doc.moveDown(0.3).font('Helvetica-Bold').text('What Didn\'t Go Well:').font('Helvetica');
        lessonsLearned.whatDidntGoWell.slice(0, 5).forEach(w => doc.text(`  ✗ ${w}`));
      }
    }

    // Footer
    doc.fontSize(8).fillColor('#999999')
      .text(`Generated by D360 — Dawat IT & Consultancy | ${new Date().toLocaleString('en-BD', { timeZone: 'Asia/Dhaka' })}`, 50, doc.page.height - 50, { align: 'center' });

    doc.end();
  });
};

module.exports = { generateClosureReportPDF };
