import { create } from 'zustand';
import { persist } from 'zustand/middleware';

const translations = {
  en: {
    // Navigation Sidebar
    dashboard: 'Dashboard',
    leads: 'Leads',
    clients: 'Clients',
    whatsapp: 'WhatsApp',
    projects: 'Projects',
    tasks: 'Tasks',
    invoices: 'Invoices',
    expenses: 'Expenses',
    reports: 'Reports',
    files: 'Files',
    proposals: 'Proposals',
    competitors: 'Competitors',
    aiHub: 'AI Hub',
    recruitment: 'Recruitment',
    sops: 'SOPs',
    hrShift: 'HR & Shift',
    settings: 'Settings',
    helpSupport: 'Help & Support',
    logout: 'Logout',
    portalCockpit: 'Portal Cockpit',
    workCockpit: 'Work Cockpit',
    mySops: 'My SOPs',
    onboardingSops: 'Onboarding SOPs',

    // Dashboard General
    welcomeBack: 'Welcome back',
    overviewSubtitle: "Here's what is happening with your business today",
    quickStats: 'Quick Statistics',
    activeClients: 'Active Clients',
    mrr: 'Monthly Revenue',
    pendingTasks: 'Upcoming Tasks',
    totalLeads: 'Total Leads',
    newThisMonth: 'New This Month',
    leadPipeline: 'Lead Pipeline',
    recentActivity: 'Recent Activity',
    activeCampaigns: 'Active Campaigns',
    quickActions: 'Quick Actions',
    viewAll: 'View all',
    live: 'Live',
    noLeadsYet: 'No leads yet',
    addFirstLead: 'Add First Lead',
    systemHealth: 'System Health',
    cloudOnline: 'Cloud: Active',
    activeChecklists: 'Active Checklists',

    // Leads Page
    leadsTitle: 'Leads',
    manageSalesPipeline: 'Manage your sales pipeline',
    addNewLead: 'Add New Lead',
    searchNameEmailPhone: 'Search name, email, phone...',
    allStatuses: 'All Statuses',
    allSources: 'All Sources',
    allScores: 'All Scores',
    export: 'Export',
    table: 'Table',
    kanban: 'Kanban',
    leadName: 'Lead',
    phone: 'Phone',
    source: 'Source',
    status: 'Status',
    score: 'Score',
    lastContact: 'Last Contact',
    assignedTo: 'Assigned To',
    convertToClient: 'Convert to Client',

    // Clients Page
    clientsTitle: 'Clients',
    manageClientRelationships: 'Manage your client relationships',
    addNewClient: 'Add New Client',
    searchClients: 'Search name, email, company...',
    allStatusesClients: 'All Statuses',
    allPackages: 'All Packages',
    clientName: 'Client',
    contact: 'Contact',
    services: 'Services',
    package: 'Package',
    health: 'Health',
    renewal: 'Renewal',
    joined: 'Joined',
  },
  bn: {
    // Navigation Sidebar
    dashboard: 'ড্যাশবোর্ড',
    leads: 'লিডসমূহ',
    clients: 'ক্লায়েন্ট তালিকা',
    whatsapp: 'হোয়াটসঅ্যাপ',
    projects: 'প্রজেক্ট সমূহ',
    tasks: 'টাস্ক তালিকা',
    invoices: 'ইনভয়েস',
    expenses: 'খরচ সমূহ',
    reports: 'রিপোর্ট',
    files: 'ফাইল পত্র',
    proposals: 'প্রস্তাবনা (প্রোপোজাল)',
    competitors: 'প্রতিযোগী ট্র্যাকিং',
    aiHub: 'এআই হাব',
    recruitment: 'নিয়োগ পোর্টাল',
    sops: 'এসওপি তালিকা',
    hrShift: 'এইচআর ও শিফট',
    settings: 'সেটিংস',
    helpSupport: 'সাহায্য ও সাপোর্ট',
    logout: 'লগআউট',
    portalCockpit: 'পোর্টাল ককপিট',
    workCockpit: 'কাজের ককপিট',
    mySops: 'আমার এসওপি',
    onboardingSops: 'অনবোর্ডিং এসওপি',

    // Dashboard General
    welcomeBack: 'স্বাগতম',
    overviewSubtitle: 'আজকে আপনার ব্যবসার সার্বিক পরিস্থিতি এখানে দেখুন',
    quickStats: 'কুইক পরিসংখ্যান',
    activeClients: 'সক্রিয় ক্লায়েন্ট',
    mrr: 'মাসিক আয় (MRR)',
    pendingTasks: 'চলতি কাজ (টাস্ক)',
    totalLeads: 'মোট লিড সংখ্যা',
    newThisMonth: 'নতুন এই মাসে',
    leadPipeline: 'লিড পাইপলাইন',
    recentActivity: 'সাম্প্রতিক কার্যক্রম',
    activeCampaigns: 'সক্রিয় ক্যাম্পেইন',
    quickActions: 'কুইক অ্যাকশন',
    viewAll: 'সব দেখুন',
    live: 'লাইভ',
    noLeadsYet: 'কোনো লিড নেই',
    addFirstLead: 'প্রথম লিড যোগ করুন',
    systemHealth: 'সিস্টেম স্ট্যাটাস',
    cloudOnline: 'ক্লাউড: সক্রিয়',
    activeChecklists: 'সক্রিয় চেকলিস্ট',

    // Leads Page
    leadsTitle: 'লিডসমূহ',
    manageSalesPipeline: 'আপনার সেলস পাইপলাইন পরিচালনা করুন',
    addNewLead: 'নতুন লিড যোগ করুন',
    searchNameEmailPhone: 'নাম, ইমেইল বা ফোন দিয়ে খুঁজুন...',
    allStatuses: 'সব স্ট্যাটাস',
    allSources: 'সব সোর্স',
    allScores: 'সব স্কোর',
    export: 'এক্সপোর্ট',
    table: 'টেবিল ভিউ',
    kanban: 'কানবান ভিউ',
    leadName: 'লিডের নাম',
    phone: 'ফোন নম্বর',
    source: 'উৎস (সোর্স)',
    status: 'অবস্থা (স্ট্যাটাস)',
    score: 'স্কোর',
    lastContact: 'শেষ যোগাযোগ',
    assignedTo: 'দায়িত্বে আছেন',
    convertToClient: 'ক্লায়েন্টে রূপান্তর করুন',

    // Clients Page
    clientsTitle: 'ক্লায়েন্ট তালিকা',
    manageClientRelationships: 'আপনার ক্লায়েন্ট সম্পর্ক পরিচালনা করুন',
    addNewClient: 'নতুন ক্লায়েন্ট যোগ করুন',
    searchClients: 'নাম, ইমেইল বা কোম্পানি দিয়ে খুঁজুন...',
    allStatusesClients: 'সব স্ট্যাটাস',
    allPackages: 'সব প্যাকেজ',
    clientName: 'ক্লায়েন্ট',
    contact: 'যোগাযোগ',
    services: 'সার্ভিস সমূহ',
    package: 'প্যাকেজ',
    health: 'হেলথ স্কোর',
    renewal: 'রিনিউয়াল তারিখ',
    joined: 'যুক্ত হয়েছেন',
  }
};

export const useLanguageStore = create(
  persist(
    (set, get) => ({
      language: 'en', // default language
      setLanguage: (lang) => set({ language: lang }),
      t: (key) => {
        const lang = get().language;
        return translations[lang]?.[key] || translations['en']?.[key] || key;
      }
    }),
    { name: 'd360-language' }
  )
);
